---
# tasks file for web_servers

- name: install apache2 package (Ubuntu)
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: install httpd package (CentOS)
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"

- name: start and enable httpd (CentOS)
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS"
