---
tasks file for web_servers
- name: print ansible_version.full
  debug:
    msg="Ansible version is {{ ansible_version.full }}"

#- name: print distro
#  debug: 
#    msg="OS distribution is {{ ansible_distribution }}"

#- name: print distro version
#  debug: 
#    msg="OS distribution version is {{ ansible_distribution_version }}"

#- name: print distro OS family
#  debug: 
#    msg="OS family is {{ ansible_os_family }}"

- name: include vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: print ansible user
  debug:
    msg="Ansible user is {{ ansible_user_id }}"

#- name: print Debian vars
#  debug: msg="{{ apache_package }} {{ php_package }}"
#  when: ansible_os_family == "Debian"

#- name: print RedHat vars
#  debug: msg="{{ apache_package }} {{ php_package }}"
#  when: ansible_os_family == "RedHat"

- name: update Debian OSs
  apt:
    update_cache: true
  changed_when: false
  when: ansible_os_family == "Debian"

- name: update RedHat OSs
  dnf:
    update_cache: true
  changed_when: false
  when: ansible_os_family == "RedHat"

#- name: install apache2 package (Ubuntu)
#  apt:
#    name:
#    - apache2
#    - libapache2-mod-php
#    state: latest
#  when: ansible_distribution == "Ubuntu"

- name: install web
  package:
    name:
    - "{{ apache_package }}"
    - "{{ php_package }}"
    state: latest
    update_cache: yes

- name: enable web
  service:
    name: "{{ apache_package }}"
    state: started
    enabled: true

- name: copy html file for site
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644

# - name: uninstall web
#   package:
#     name:
#       - "{{ apache_package }}"
#       - "{{ php_package }}"
#     state: absent