---
# tasks file for web_servers
- name: print distro
  debug: 
    msg="{{ ansible_distribution }}"

- name: print distro version
  debug: 
    msg="{{ ansible_distribution_version }}"

- name: print distro OS family
  debug: 
    msg="{{ ansible_os_family }}"

- name: include vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: print Debian vars
  debug: msg="{{ apache_package }} {{ php_package }}"
  when: ansible_os_family == "Debian"

- name: print RedHat vars
  debug: msg="{{ apache_package }} {{ php_package }}"
  when: ansible_os_family == "RedHat"

- name: update Debian OSs
  apt:
    update_cache: true
    cache_valid_time: 86400
  when: ansible_os_family == "Debian"

#- name: install apache2 package (Ubuntu)
#  apt:
#    name:
#    - apache2
#    - libapache2-mod-php
#    state: latest
#  when: ansible_distribution == "Ubuntu"

- name: install web
  package:
    name:
    - "{{ apache_package }}"
    - "{{ php_package }}"
    state: present

- name: enable web
  service:
    name: "{{ apache_package }}"
    state: started
    enabled: true
