---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: "Check if UNZIP is installed"
    package_facts:
      manager: "auto"

  - name: "UNZIP test result"
    debug: 
      msg: "UNZIP found"
    when: "'unzip' in ansible_facts.packages"

  - name: "UNZIP test result"
    debug: 
      msg: "UNZIP NOT found"
    when: "'unzip' not in ansible_facts.packages"

  - name: ls -d /usr/local/bin/terraform*
    find:
      paths: /usr/local/bin
      patterns: "terraform*"
      recurse: no
      file_type: any
    register: found_directories

  - debug:
      msg: "{{ [item.path] }} "
    with_items: "{{ found_directories.files }}"
