---
# tasks file for base
- name: add shh key for simone
  authorized_key:
    user: simone
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMGd3rlcvbdLW2y9fH2Z7tTgl9Yko8vx6kkbaVMRpbWi ansible"

- name: generate sshd_config file from template
  tags: ssh
  template:
    src:  "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
