---
- name: Converge
  hosts: all
  
  tasks:
    - name: "Include ns.web_servers"
      include_role: 
        name: "ns.web_servers"

    - name: Create default file
      copy:
        dest: /var/www/html/index.html
        mode: 0644
        owner: root
        group: root
        content: |
          <html>
          <head><title>Hello world!</title></head>
          <body>Hello world!</body>
          </html>
