---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all

  tasks:
  - name: Verify Apache is serving web requests.
    uri:
      url: http://localhost/
      status_code: 200

  - name: Verify the page return status 200 and fail if word 'world' is not in the page content
    uri:
      url: http://localhost/
      return_content: yes
    register: this
    failed_when: "'world' not in this.content"

  - name: Verify the page return status 200 and fail if word 'animal' is not in the page content
    uri:
      url: http://localhost/
      return_content: yes
    register: this
    failed_when: "'animal' not in this.content"

