---
# tasks file for db_servers

- name: include vars
  include_vars: "{{ ansible_os_family }}.yml"

# - name: print Debian vars
#   debug: msg="{{ mariadb_server }}"
#   when: ansible_os_family == "Debian"

# - name: print RedHat vars
#   debug: msg="{{ mariadb_server }}"
#   when: ansible_os_family == "RedHat"

- name: install mariadb server
  package:
    name: "{{ mariadb_server }}"
    state: latest
    update_cache: yes
