---

- hosts: web_servers
  become: true
  tasks:

  - name: remove apache2 package (Ubuntu)
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: remove httpd package (Ubuntu)
    dnf:
      name:
        - httpd
        - php
      state: absent
    when: ansible_distribution == "CentOS"
